name: Build & Push Docker Image - Suivi Academique

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: suivi_api

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # 1️⃣ Récupération du code
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2️⃣ Installation Java
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # 3️⃣ Cache Maven (pipeline plus rapide)
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}

      # 4️⃣ Build Maven
      - name: Build Spring Boot app
        run: mvn clean package -DskipTests

      # 5️⃣ Analyse SonarQube (LOCAL & SAFE)
      - name: SonarQube Analysis
        run: mvn sonar:sonar -Dsonar.host.url="${{ secrets.SONAR_HOST_URL }}" -Dsonar.login="${{ secrets.SONAR_TOKEN }}"

      # 6️⃣ Login Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 7️⃣ Build & Push Docker Image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/suivi_api:latest
            ${{ secrets.DOCKER_USERNAME }}/suivi_api:${{ github.sha }}
